//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonenVerwaltung.BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ort
    {
        public Ort()
        {
            this.AllePersonen = new HashSet<Person>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int PLZ { get; set; }
    
        public virtual ICollection<Person> AllePersonen { get; set; }
    }
}
